"""Markdown rendering for BTC5 autoresearch cycle artifacts."""

from __future__ import annotations

import json
from typing import Any


def render_cycle_markdown(payload: dict[str, Any]) -> str:
    md_lines = [
        "# BTC5 Autoresearch Cycle",
        "",
        f"- Generated at: `{payload['generated_at']}`",
        f"- Action: `{payload['decision']['action']}`",
        f"- Deploy recommendation: `{payload.get('deploy_recommendation', 'hold')}`",
        f"- Reason: `{payload['decision']['reason']}`",
        f"- Lab action: `{payload['decision'].get('lab_action', payload['decision']['action'])}`",
        f"- Lab reason: `{payload['decision'].get('lab_reason', payload['decision']['reason'])}`",
        f"- Probe gate applied: `{payload['decision'].get('probe_gate_applied', False)}`",
        f"- Probe gate reasons: `{'; '.join(payload['decision'].get('probe_gate_reason_tags') or ['none'])}`",
        f"- Selected source: `{payload['decision'].get('selected_source', 'none')}`",
        f"- Selected family: `{payload['decision'].get('selected_family', 'none')}`",
        f"- Chosen public forecast source: `{payload.get('public_forecast_source_artifact', 'none')}`",
        f"- Public forecast selection reason: `{(payload.get('public_forecast_selection') or {}).get('selection_reason', 'none')}`",
        f"- Active profile: `{payload['active_profile']['name']}`",
        f"- Best profile: `{payload['best_candidate']['profile']['name'] if payload.get('best_candidate') else 'none'}`",
        f"- Package confidence: `{payload.get('package_confidence_label', 'low')}`",
        f"- Selected package confidence: `{payload.get('selected_package_confidence_label', payload.get('package_confidence_label', 'low'))}`",
        f"- Package confidence reasons: `{'; '.join(payload.get('package_confidence_reasons') or ['none'])}`",
        f"- Selected package confidence reasons: `{'; '.join(payload.get('selected_package_confidence_reasons') or payload.get('package_confidence_reasons') or ['none'])}`",
        f"- Capital scale recommendation: `{(payload.get('capital_scale_recommendation') or {}).get('status', 'hold')}`",
        f"- Capital stage recommendation: `stage {(payload.get('capital_stage_recommendation') or {}).get('recommended_stage', 1)}`",
        f"- Size-aware live stage cap: `{((payload.get('size_aware_deployment') or {}).get('recommended_live_stage_cap') or 0)}`",
        f"- Best live package source: `{(payload.get('best_live_package') or {}).get('source', 'none')}`",
        f"- Best raw package source: `{(payload.get('best_raw_research_package') or {}).get('source', 'none')}`",
        f"- One-sided bias recommendation: `{(payload.get('one_sided_bias_recommendation') or {}).get('recommendation', 'balanced_directional_bias')}`",
        f"- Observed window rows: `{payload['simulation_summary']['input']['observed_window_rows']}`",
        f"- Observed live-filled rows: `{payload['simulation_summary']['input']['live_filled_rows']}`",
        "",
        "## Deltas",
        "",
        f"- Median continuation ARR delta: `{payload['decision'].get('median_arr_delta_pct', 0.0):.2f}` percentage points",
        f"- Historical continuation ARR delta: `{payload['decision'].get('historical_arr_delta_pct', 0.0):.2f}` percentage points",
        f"- P05 continuation ARR delta: `{payload['decision'].get('p05_arr_delta_pct', 0.0):.2f}` percentage points",
        f"- Replay PnL delta: `{payload['decision'].get('replay_pnl_delta_usd', 0.0):.4f}` USD",
        f"- Median Monte Carlo PnL delta: `{payload['decision'].get('median_pnl_delta_usd', 0.0):.4f}` USD",
        f"- Profit-probability delta: `{payload['decision'].get('profit_probability_delta', 0.0):.2%}`",
        f"- P95 drawdown delta: `{payload['decision'].get('p95_drawdown_delta_usd', 0.0):.4f}` USD",
        f"- Loss-hit delta: `{payload['decision'].get('loss_hit_probability_delta', 0.0):.2%}`",
        f"- Fill lift: `{payload['decision'].get('fill_lift', 0)}`",
        "",
        "## Recommended Session Policy",
        "",
        f"- Runtime-ready policy records: `{len(payload.get('recommended_session_policy') or [])}`",
        "",
        "```json",
        json.dumps(payload.get("recommended_session_policy") or [], indent=2, sort_keys=True),
        "```",
        "",
        "## Runtime Package",
        "",
        f"- Active package profile: `{((payload.get('active_runtime_package') or {}).get('profile') or {}).get('name', 'none')}`",
        f"- Active package session-policy records: `{len(((payload.get('active_runtime_package') or {}).get('session_policy') or []))}`",
        f"- Selected active package profile: `{((payload.get('selected_active_runtime_package') or {}).get('profile') or {}).get('name', 'none')}`",
        f"- Best package profile: `{((payload.get('best_runtime_package') or {}).get('profile') or {}).get('name', 'none')}`",
        f"- Best package session-policy records: `{len(((payload.get('best_runtime_package') or {}).get('session_policy') or []))}`",
        f"- Selected best package profile: `{((payload.get('selected_best_runtime_package') or {}).get('profile') or {}).get('name', 'none')}`",
        f"- Validation live-filled rows: `{payload.get('validation_live_filled_rows', 0)}`",
        f"- Generalization ratio: `{payload.get('generalization_ratio', 0.0):.4f}`",
        f"- Promoted package selected: `{payload.get('promoted_package_selected')}`",
        "",
        "## Execution Drag",
        "",
        f"- Skip-price count: `{((payload.get('execution_drag_summary') or {}).get('skip_price_count', 0))}`",
        f"- Order-failed count: `{((payload.get('execution_drag_summary') or {}).get('order_failed_count', 0))}`",
        f"- Cancelled-unfilled count: `{((payload.get('execution_drag_summary') or {}).get('cancelled_unfilled_count', 0))}`",
        f"- Skip-rate penalty: `{((payload.get('best_live_package') or {}).get('skip_rate_penalty', 0.0))}`",
        f"- Order-failure penalty: `{((payload.get('best_live_package') or {}).get('order_failure_penalty', 0.0))}`",
        f"- Winner changed by drag: `{((payload.get('execution_drag_summary') or {}).get('winner_changed_due_to_execution_drag', False))}`",
        "",
        "## Runtime Load Status",
        "",
        f"- Override env written: `{((payload.get('runtime_load_status') or {}).get('override_env_written'))}`",
        f"- Override env path: `{((payload.get('runtime_load_status') or {}).get('override_env_path') or 'none')}`",
        f"- Runtime session-policy records: `{((payload.get('runtime_load_status') or {}).get('session_policy_records'))}`",
        f"- Base env changed: `{((payload.get('runtime_load_status') or {}).get('base_env_changed'))}`",
        f"- Service restart requested: `{((payload.get('runtime_load_status') or {}).get('service_restart_requested'))}`",
        f"- Service restart state: `{((payload.get('runtime_load_status') or {}).get('service_restart_state') or 'none')}`",
        "",
        "## Size-Aware Deployment",
        "",
        f"- Size summary available: `{((payload.get('size_aware_deployment') or {}).get('available', False))}`",
        f"- Capacity profile label: `{((payload.get('size_aware_deployment') or {}).get('capacity_profile_label') or 'none')}`",
        f"- Capacity profile name: `{((payload.get('size_aware_deployment') or {}).get('capacity_profile_name') or 'none')}`",
        f"- Match reason: `{((payload.get('size_aware_deployment') or {}).get('match_reason') or 'none')}`",
        f"- Recommended live stage cap: `{((payload.get('size_aware_deployment') or {}).get('recommended_live_stage_cap') or 0)}`",
        f"- Recommended live trade-size cap (USD): `{((payload.get('size_aware_deployment') or {}).get('recommended_live_trade_size_cap_usd') or 0)}`",
        "",
        "## Package Decision",
        "",
        f"- Deploy recommendation: `{payload.get('deploy_recommendation', 'hold')}`",
        f"- Evidence missing: `{'; '.join(payload.get('package_missing_evidence') or ['none'])}`",
        f"- Recommendation explanation: `{payload.get('decision', {}).get('reason', 'none')}`",
        f"- Capital tranche recommendation: `{((payload.get('capital_scale_recommendation') or {}).get('recommended_tranche_usd', 0))}` USD",
        f"- Capital reason: `{((payload.get('capital_scale_recommendation') or {}).get('reason') or 'none')}`",
        f"- Capital stage: `{((payload.get('capital_stage_recommendation') or {}).get('recommended_stage', 1))}`",
        f"- Capital stage max trade (USD): `{((payload.get('capital_stage_recommendation') or {}).get('recommended_max_trade_usd', 10))}`",
        f"- Stage guardrails passed: `{((payload.get('capital_stage_recommendation') or {}).get('promotion_guardrails_passed', False))}`",
        f"- Stage reason: `{((payload.get('capital_stage_recommendation') or {}).get('stage_reason') or 'none')}`",
        "",
        "## Package Ranking",
        "",
        f"- Live-candidate count: `{(((payload.get('package_ranking') or {}).get('package_set_breakdown') or {}).get('live_candidate', 0))}`",
        f"- Shadow-only count: `{(((payload.get('package_ranking') or {}).get('package_set_breakdown') or {}).get('shadow_only', 0))}`",
        f"- Hold-current count: `{(((payload.get('package_ranking') or {}).get('package_set_breakdown') or {}).get('hold_current', 0))}`",
        f"- Suppress count: `{(((payload.get('package_ranking') or {}).get('package_set_breakdown') or {}).get('suppress', 0))}`",
        f"- Top package set: `{((payload.get('package_ranking') or {}).get('top_package_set') or 'none')}`",
        "",
        "```json",
        json.dumps(((payload.get("package_ranking") or {}).get("ranked_packages") or [])[:5], indent=2, sort_keys=True),
        "```",
        "",
        "## Best Candidate",
        "",
        json.dumps(payload.get("best_candidate") or {}, indent=2, sort_keys=True),
    ]
    return "\n".join(md_lines) + "\n"
