#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import shlex
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from bot.runtime_profile import load_runtime_profile, write_effective_runtime_profile


DEFAULT_REPORTS_DIR = Path("reports")
DEFAULT_OVERRIDES_ENV_PATH = DEFAULT_REPORTS_DIR / "runtime_operator_overrides.env"
DEFAULT_EFFECTIVE_PATH = DEFAULT_REPORTS_DIR / "runtime_profile_effective.json"
DEFAULT_ACTION_DIR = DEFAULT_REPORTS_DIR / "operator_actions"
DEFAULT_ACTION_PREFIX = "runtime_control"
MAX_HOURLY_NOTIONAL_BUDGET_USD = 500.0

OPERATOR_ENV_KEYS = (
    "JJ_YES_THRESHOLD",
    "JJ_NO_THRESHOLD",
    "JJ_MAX_RESOLUTION_HOURS",
    "JJ_HOURLY_NOTIONAL_BUDGET_USD",
    "JJ_MAX_POSITION_USD",
    "JJ_ENABLE_POLYMARKET_VENUE",
    "JJ_ENABLE_KALSHI_VENUE",
)


class RuntimeControlError(ValueError):
    """Raised when operator command inputs are invalid."""


def _iso_utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _parse_bool(value: str) -> str:
    normalized = str(value).strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return "true"
    if normalized in {"0", "false", "no", "off"}:
        return "false"
    raise RuntimeControlError(f"invalid boolean value: {value!r}")


def _parse_float(value: Any, *, field_name: str) -> float:
    try:
        return float(str(value).strip())
    except ValueError as exc:
        raise RuntimeControlError(f"{field_name} must be a number") from exc


def _parse_overrides_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    overrides: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        overrides[key] = value.strip()
    return overrides


def _write_env_overrides(path: Path, overrides: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Runtime operator overrides generated by scripts/runtime_controls.py",
        f"# generated_at={_iso_utc_now()}",
    ]
    for key in sorted(overrides):
        lines.append(f"{key}={overrides[key]}")
    path.write_text("\n".join(lines) + "\n")


def _validate_threshold(name: str, value: float) -> None:
    if not 0.0 <= value <= 1.0:
        raise RuntimeControlError(f"{name} must be in [0, 1], got {value}")


def _validate_max_resolution_hours(value: float) -> None:
    if value <= 0.0 or value > 168.0:
        raise RuntimeControlError(f"max-resolution-hours must be in (0, 168], got {value}")


def _validate_hourly_notional_budget(value: float) -> None:
    if value < 0.0:
        raise RuntimeControlError(f"hourly-notional-budget-usd must be >= 0, got {value}")
    if value > MAX_HOURLY_NOTIONAL_BUDGET_USD:
        raise RuntimeControlError(
            f"hourly-notional-budget-usd exceeds ceiling {MAX_HOURLY_NOTIONAL_BUDGET_USD:.2f}: {value}"
        )


def _validate_per_trade_cap(value: float) -> None:
    if value <= 0.0:
        raise RuntimeControlError(f"per-trade-cap-usd must be > 0, got {value}")


def _validate_cross_field(hourly_budget: float, per_trade_cap: float) -> None:
    if hourly_budget > 0.0 and per_trade_cap > hourly_budget:
        raise RuntimeControlError(
            f"per-trade-cap-usd ({per_trade_cap}) cannot exceed hourly-notional-budget-usd ({hourly_budget})"
        )


def _build_env_updates(args: argparse.Namespace, current_overrides: dict[str, str]) -> dict[str, str]:
    updates: dict[str, str] = {}

    if args.command == "adjust-threshold":
        threshold_value = _parse_float(args.value, field_name="value")
        _validate_threshold("threshold", threshold_value)
        env_key = "JJ_YES_THRESHOLD" if args.side == "yes" else "JJ_NO_THRESHOLD"
        updates[env_key] = f"{threshold_value:g}"
    elif args.command == "deploy-budget":
        budget_value = _parse_float(args.budget_usd, field_name="budget-usd")
        _validate_hourly_notional_budget(budget_value)
        updates["JJ_HOURLY_NOTIONAL_BUDGET_USD"] = f"{budget_value:g}"

        resolution_value = _parse_float(args.max_resolution_hours, field_name="max-resolution-hours")
        _validate_max_resolution_hours(resolution_value)
        updates["JJ_MAX_RESOLUTION_HOURS"] = f"{resolution_value:g}"

        if args.per_trade_cap_usd is not None:
            per_trade_cap = _parse_float(args.per_trade_cap_usd, field_name="per-trade-cap-usd")
            _validate_per_trade_cap(per_trade_cap)
            _validate_cross_field(budget_value, per_trade_cap)
            updates["JJ_MAX_POSITION_USD"] = f"{per_trade_cap:g}"
    elif args.command == "set-controls":
        if args.yes_threshold is not None:
            yes_value = _parse_float(args.yes_threshold, field_name="yes-threshold")
            _validate_threshold("yes-threshold", yes_value)
            updates["JJ_YES_THRESHOLD"] = f"{yes_value:g}"
        if args.no_threshold is not None:
            no_value = _parse_float(args.no_threshold, field_name="no-threshold")
            _validate_threshold("no-threshold", no_value)
            updates["JJ_NO_THRESHOLD"] = f"{no_value:g}"
        if args.max_resolution_hours is not None:
            resolution_value = _parse_float(args.max_resolution_hours, field_name="max-resolution-hours")
            _validate_max_resolution_hours(resolution_value)
            updates["JJ_MAX_RESOLUTION_HOURS"] = f"{resolution_value:g}"
        if args.hourly_notional_budget_usd is not None:
            budget_value = _parse_float(args.hourly_notional_budget_usd, field_name="hourly-notional-budget-usd")
            _validate_hourly_notional_budget(budget_value)
            updates["JJ_HOURLY_NOTIONAL_BUDGET_USD"] = f"{budget_value:g}"
        if args.per_trade_cap_usd is not None:
            per_trade_cap = _parse_float(args.per_trade_cap_usd, field_name="per-trade-cap-usd")
            _validate_per_trade_cap(per_trade_cap)
            updates["JJ_MAX_POSITION_USD"] = f"{per_trade_cap:g}"
        if args.enable_polymarket is not None:
            updates["JJ_ENABLE_POLYMARKET_VENUE"] = _parse_bool(args.enable_polymarket)
        if args.enable_kalshi is not None:
            updates["JJ_ENABLE_KALSHI_VENUE"] = _parse_bool(args.enable_kalshi)
    else:
        raise RuntimeControlError(f"unsupported command: {args.command}")

    if not updates:
        raise RuntimeControlError("no updates requested")

    merged = dict(current_overrides)
    merged.update(updates)

    hourly_budget = _parse_float(merged.get("JJ_HOURLY_NOTIONAL_BUDGET_USD", "0"), field_name="JJ_HOURLY_NOTIONAL_BUDGET_USD")
    per_trade_cap = _parse_float(merged.get("JJ_MAX_POSITION_USD", "5"), field_name="JJ_MAX_POSITION_USD")
    _validate_hourly_notional_budget(hourly_budget)
    _validate_per_trade_cap(per_trade_cap)
    _validate_cross_field(hourly_budget, per_trade_cap)

    return updates


def _extract_scope(bundle: Any) -> dict[str, Any]:
    return {
        "selected_profile": bundle.selected_profile,
        "mode": bundle.config.get("mode", {}),
        "signal_thresholds": bundle.config.get("signal_thresholds", {}),
        "market_filters": bundle.config.get("market_filters", {}),
        "risk_limits": bundle.config.get("risk_limits", {}),
        "feature_flags": bundle.config.get("feature_flags", {}),
    }


def _build_action_payload(
    *,
    args: argparse.Namespace,
    command_line: str,
    before_bundle: Any,
    after_bundle: Any,
    updates: dict[str, str],
) -> dict[str, Any]:
    changed: list[dict[str, Any]] = []
    for env_key in OPERATOR_ENV_KEYS:
        before_value = before_bundle.effective_env.get(env_key)
        after_value = after_bundle.effective_env.get(env_key)
        if env_key in updates or before_value != after_value:
            changed.append(
                {
                    "env_var": env_key,
                    "old": before_value,
                    "new": after_value,
                }
            )

    return {
        "generated_at": _iso_utc_now(),
        "operator_action": {
            "command": args.command,
            "argv": command_line,
            "profile": args.profile,
            "changed_values": changed,
            "requested_updates": dict(sorted(updates.items())),
        },
        "effective_scope": {
            "before": _extract_scope(before_bundle),
            "after": _extract_scope(after_bundle),
        },
    }


def _write_action_artifact(
    *,
    action_dir: Path,
    action_prefix: str,
    payload: dict[str, Any],
) -> Path:
    action_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = action_dir / f"{action_prefix}_{ts}.json"
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return path


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Atomic operator controls for runtime thresholds, risk limits, and venue flags."
    )
    parser.add_argument(
        "--profile",
        default="blocked_safe",
        help="Runtime profile name used as the base before env overrides.",
    )
    parser.add_argument(
        "--reports-dir",
        default=str(DEFAULT_REPORTS_DIR),
        help=f"Reports directory (default: {DEFAULT_REPORTS_DIR}).",
    )
    parser.add_argument(
        "--overrides-path",
        default=None,
        help="Path to persisted operator env overrides (default: <reports-dir>/runtime_operator_overrides.env).",
    )
    parser.add_argument(
        "--effective-path",
        default=None,
        help="Path to runtime_profile_effective.json output (default: <reports-dir>/runtime_profile_effective.json).",
    )
    parser.add_argument(
        "--action-dir",
        default=None,
        help="Directory for timestamped operator action artifacts (default: <reports-dir>/operator_actions).",
    )
    parser.add_argument(
        "--action-prefix",
        default=DEFAULT_ACTION_PREFIX,
        help=f"Filename prefix for action artifacts (default: {DEFAULT_ACTION_PREFIX}).",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    adjust = subparsers.add_parser("adjust-threshold", help="Adjust one side threshold.")
    adjust.add_argument("--side", choices=("yes", "no"), required=True, help="Threshold side to update.")
    adjust.add_argument("--value", required=True, help="New threshold value in [0, 1].")

    deploy = subparsers.add_parser("deploy-budget", help="Set bounded campaign budget and market horizon.")
    deploy.add_argument("--budget-usd", required=True, help="Rolling 60-minute notional budget cap in USD.")
    deploy.add_argument(
        "--max-resolution-hours",
        required=True,
        help="Hard max resolution horizon for campaign-qualified markets.",
    )
    deploy.add_argument("--per-trade-cap-usd", default=None, help="Optional per-trade cap in USD.")

    set_controls = subparsers.add_parser("set-controls", help="Atomically set runtime controls in one command.")
    set_controls.add_argument("--yes-threshold", default=None)
    set_controls.add_argument("--no-threshold", default=None)
    set_controls.add_argument("--max-resolution-hours", default=None)
    set_controls.add_argument("--hourly-notional-budget-usd", default=None)
    set_controls.add_argument("--per-trade-cap-usd", default=None)
    set_controls.add_argument("--enable-polymarket", default=None, help="Boolean flag (true/false).")
    set_controls.add_argument("--enable-kalshi", default=None, help="Boolean flag (true/false).")

    return parser


def main(argv: list[str] | None = None) -> int:
    try:
        parser = _build_parser()
        args = parser.parse_args(argv)

        reports_dir = Path(args.reports_dir)
        overrides_path = (
            Path(args.overrides_path) if args.overrides_path else reports_dir / DEFAULT_OVERRIDES_ENV_PATH.name
        )
        effective_path = Path(args.effective_path) if args.effective_path else reports_dir / DEFAULT_EFFECTIVE_PATH.name
        action_dir = Path(args.action_dir) if args.action_dir else reports_dir / DEFAULT_ACTION_DIR.name

        current_overrides = _parse_overrides_env(overrides_path)
        updates = _build_env_updates(args, current_overrides)

        before_bundle = load_runtime_profile(env={"JJ_RUNTIME_PROFILE": args.profile, **current_overrides})

        merged_overrides = dict(current_overrides)
        merged_overrides.update(updates)
        merged_env = {"JJ_RUNTIME_PROFILE": args.profile, **merged_overrides}
        after_bundle = load_runtime_profile(env=merged_env)

        command_line = " ".join(shlex.quote(token) for token in (argv or []))
        action_payload = _build_action_payload(
            args=args,
            command_line=command_line,
            before_bundle=before_bundle,
            after_bundle=after_bundle,
            updates=updates,
        )

        _write_env_overrides(overrides_path, merged_overrides)
        write_effective_runtime_profile(after_bundle, output_path=effective_path)
        action_path = _write_action_artifact(
            action_dir=action_dir,
            action_prefix=args.action_prefix,
            payload=action_payload,
        )

        print(json.dumps({"effective_profile": str(effective_path), "operator_action": str(action_path)}, sort_keys=True))
        return 0
    except RuntimeControlError as exc:
        print(str(exc), file=sys.stderr)
        return 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
