#!/usr/bin/env python3
"""
Tournament Engine — Parallel Local Backtesting at Scale
========================================================
Takes a population of strategy genomes and evaluates them all against
historical data using every available CPU core. Returns ranked results
with kill-rule enforcement and statistical significance testing.

This is the compute layer. It doesn't decide what to test (that's the
Evolution Loop). It doesn't decide what to promote (that's the Promotion
Manager). It answers one question: given these N strategy variants,
which ones survive?

Architecture:
  - Each genome is evaluated independently (embarrassingly parallel)
  - Each evaluation runs the full backtest pipeline:
    1. Generate signals from genome-weighted sources
    2. Filter by genome-encoded rules
    3. Size positions by genome Kelly/confidence
    4. Simulate fills with maker/taker cost models
    5. Compute fitness: Sharpe × sqrt(fills) × (1 - max_DD)
  - Kill rules applied post-evaluation (not during — let them run)
  - Results ranked by fitness with statistical significance noted

Fitness function rationale:
  Sharpe alone rewards low-activity strategies that get lucky on 3 trades.
  Sharpe × sqrt(fills) rewards strategies that find MANY profitable trades.
  The (1 - max_DD) penalty prevents strategies that are right on average
  but have drawdowns that would blow the account.

March 2026 — Elastifund / JJ
"""
from __future__ import annotations

import json
import logging
import math
import os
import sqlite3
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from multiprocessing import cpu_count
from pathlib import Path
from typing import Any, Optional

from bot.strategy_genome import GeneType, StrategyGenome

logger = logging.getLogger("JJ.tournament_engine")


# ---------------------------------------------------------------------------
# Evaluation result
# ---------------------------------------------------------------------------

@dataclass
class TournamentResult:
    genome_id: str
    fitness: float
    win_rate: float
    total_signals: int
    total_fills: int
    gross_pnl: float
    sharpe: float
    max_drawdown: float
    profit_factor: float
    kelly_fraction: float
    p_value: float
    kill_reasons: list[str] = field(default_factory=list)
    survived: bool = True
    eval_time_ms: float = 0.0
    details: dict[str, Any] = field(default_factory=dict)


@dataclass
class TournamentReport:
    """Summary of a tournament round."""
    tournament_id: str
    started_at: str
    completed_at: str
    population_size: int
    survived_count: int
    killed_count: int
    best_fitness: float
    best_genome_id: str
    median_fitness: float
    results: list[TournamentResult] = field(default_factory=list)
    eval_time_total_ms: float = 0.0
    cores_used: int = 1


# ---------------------------------------------------------------------------
# Genome evaluator (runs in subprocess)
# ---------------------------------------------------------------------------

def _evaluate_genome_worker(args: tuple) -> dict:
    """
    Worker function for parallel evaluation.

    Takes a serialized genome + historical data reference and returns
    a TournamentResult as a dict (for pickle compatibility).

    This function runs in a separate process. It must be self-contained
    and not reference module-level state that can't be pickled.
    """
    genome_dict, data_path, config = args
    t0 = time.monotonic()

    # Ensure repo root is on path in subprocess
    import sys
    repo_root = os.environ.get("ELASTIFUND_ROOT", "")
    if repo_root and repo_root not in sys.path:
        sys.path.insert(0, repo_root)

    try:
        result = _run_backtest(genome_dict, data_path, config)
    except Exception as e:
        result = {
            "genome_id": genome_dict.get("genome_id", "unknown"),
            "fitness": -999.0,
            "win_rate": 0.0,
            "total_signals": 0,
            "total_fills": 0,
            "gross_pnl": 0.0,
            "sharpe": 0.0,
            "max_drawdown": 1.0,
            "profit_factor": 0.0,
            "kelly_fraction": 0.0,
            "p_value": 1.0,
            "kill_reasons": [f"eval_error: {str(e)[:200]}"],
            "survived": False,
            "details": {},
        }

    result["eval_time_ms"] = (time.monotonic() - t0) * 1000
    return result


def _run_backtest(genome_dict: dict, data_path: str, config: dict) -> dict:
    """
    Core backtest logic for a single genome.

    Simulates the genome's trading strategy against historical market data.
    Uses a simplified but realistic model:
    - Signals generated by weighting multiple sources
    - Filtered by genome-encoded rules
    - Sized by Kelly/confidence
    - P&L computed with maker/taker cost model
    """
    genes = genome_dict.get("genes", {})
    genome_id = genome_dict.get("genome_id", "unknown")

    # Load historical data
    data = _load_data(data_path)
    if not data:
        return _empty_result(genome_id, "no_data")

    # Extract gene values with defaults
    def g(name: str, default: float = 0.0) -> float:
        entry = genes.get(name, {})
        return float(entry.get("value", default))

    # Phase 1: Signal generation
    # Each "market" in data has features from multiple signal sources.
    # The genome weights these sources and requires minimum agreement.
    signals = []
    for market in data:
        signal = _generate_composite_signal(market, genes)
        if signal is not None:
            signals.append(signal)

    if len(signals) < 5:
        return _empty_result(genome_id, "insufficient_signals")

    # Phase 2: Filtering
    filtered = []
    for sig in signals:
        # Time filter
        hour = sig.get("hour_et", 12)
        h_start = int(g("hour_start_et", 0))
        h_end = int(g("hour_end_et", 23))
        if h_start <= h_end:
            if not (h_start <= hour <= h_end):
                continue
        else:  # wrap-around (e.g., 22 to 4)
            if not (hour >= h_start or hour <= h_end):
                continue

        # VPIN filter
        vpin = sig.get("vpin", 0.0)
        if vpin > g("max_vpin", 0.60):
            continue

        # Spread filter
        spread = sig.get("spread", 0.05)
        if spread < g("min_spread", 0.02) or spread > g("max_spread", 0.15):
            continue

        # Price filter
        price = sig.get("entry_price", 0.5)
        if price < g("min_entry_price", 0.85) or price > g("max_entry_price", 0.95):
            continue

        # Direction bias filter
        bias = g("direction_bias", 0.0)
        side = sig.get("side", "YES")
        if bias > 0.3 and side == "NO":
            continue
        if bias < -0.3 and side == "YES":
            continue

        # Confidence filter
        if sig.get("confidence", 0.5) < g("min_confidence", 0.55):
            continue

        # Edge filter
        if sig.get("edge", 0.0) < g("min_edge", 0.05):
            continue

        # Book imbalance filter
        book_imb = abs(sig.get("book_imbalance", 0.0))
        if book_imb < g("min_book_imbalance", 0.0):
            continue

        filtered.append(sig)

    if len(filtered) < 3:
        return _empty_result(genome_id, "all_filtered")

    # Phase 3: Position sizing and P&L simulation
    pnls = []
    wins = 0
    gross_wins = 0.0
    gross_losses = 0.0
    kelly_frac = g("kelly_fraction", 0.25)
    max_pos = g("max_position_usd", 5.0)
    conf_scale = g("confidence_scaling", 1.0)
    maker_only = g("maker_only", 1.0) > 0.5

    for sig in filtered:
        # Size: Kelly × confidence_scaling × confidence
        confidence = sig.get("confidence", 0.55)
        raw_size = kelly_frac * (1 + conf_scale * (confidence - 0.5)) * max_pos
        size = max(1.0, min(max_pos, raw_size))

        # P&L calculation
        price = sig.get("entry_price", 0.5)
        outcome = sig.get("outcome", "unknown")
        side = sig.get("side", "YES")

        won = (side == "YES" and outcome == "YES_WON") or \
              (side == "NO" and outcome == "NO_WON")

        if won:
            payout = size * (1.0 - price) / price  # Binary option payout
            fee = size * price * (1 - price) * 0.02 if not maker_only else 0.0
            trade_pnl = payout - fee
            gross_wins += abs(trade_pnl)
        else:
            trade_pnl = -size
            gross_losses += abs(trade_pnl)

        pnls.append(trade_pnl)
        if won:
            wins += 1

    n = len(pnls)
    if n == 0:
        return _empty_result(genome_id, "no_fills")

    # Phase 4: Compute metrics
    total_pnl = sum(pnls)
    win_rate = wins / n if n > 0 else 0.0

    # Sharpe
    if n >= 2:
        mean_pnl = total_pnl / n
        var_pnl = sum((p - mean_pnl) ** 2 for p in pnls) / n
        std_pnl = math.sqrt(var_pnl) if var_pnl > 0 else 0.001
        sharpe = mean_pnl / std_pnl * math.sqrt(252)  # Annualized
    else:
        sharpe = 0.0

    # Max drawdown
    cumulative = 0.0
    peak = 0.0
    max_dd = 0.0
    for p in pnls:
        cumulative += p
        if cumulative > peak:
            peak = cumulative
        dd = (peak - cumulative) / max(peak, 1.0) if peak > 0 else 0.0
        if dd > max_dd:
            max_dd = dd

    # Profit factor
    pf = gross_wins / gross_losses if gross_losses > 0 else (10.0 if gross_wins > 0 else 0.0)

    # Kelly from observed data
    if win_rate > 0 and pf > 0:
        b = pf
        q = 1.0 - win_rate
        kelly = max(0.0, (b * win_rate - q) / b)
    else:
        kelly = 0.0

    # Binomial p-value (is this better than coin flip?)
    p_value = _binomial_p(n, wins, 0.50)

    # Phase 5: Fitness calculation
    # Sharpe × sqrt(fills) × (1 - max_DD) × sign(PnL)
    dd_penalty = max(0.01, 1.0 - max_dd)
    volume_bonus = math.sqrt(max(1, n))
    raw_fitness = sharpe * volume_bonus * dd_penalty
    if total_pnl < 0:
        raw_fitness = raw_fitness * 0.1  # Heavy penalty for losing strategies

    # Phase 6: Kill rules (lenient during evolution, strict at promotion)
    kill_reasons = []
    if n < 5:
        kill_reasons.append("insufficient_fills")
    if win_rate < 0.45 and n >= 30:
        kill_reasons.append("negative_wr_at_scale")
    if max_dd > 0.50:
        kill_reasons.append("excessive_drawdown")
    if pf < 0.80 and n >= 30:
        kill_reasons.append("profit_factor_collapse")
    if total_pnl < -20.0:
        kill_reasons.append("large_loss")

    survived = len(kill_reasons) == 0

    return {
        "genome_id": genome_id,
        "fitness": round(raw_fitness, 6),
        "win_rate": round(win_rate, 4),
        "total_signals": len(signals),
        "total_fills": n,
        "gross_pnl": round(total_pnl, 2),
        "sharpe": round(sharpe, 4),
        "max_drawdown": round(max_dd, 4),
        "profit_factor": round(pf, 4),
        "kelly_fraction": round(kelly, 6),
        "p_value": round(p_value, 6),
        "kill_reasons": kill_reasons,
        "survived": survived,
        "details": {
            "gross_wins": round(gross_wins, 2),
            "gross_losses": round(gross_losses, 2),
            "filtered_signals": len(filtered),
            "raw_signals": len(signals),
        },
    }


def _generate_composite_signal(market: dict, genes: dict) -> Optional[dict]:
    """
    Generate a composite signal from weighted signal sources.

    Each market has pre-computed features from multiple signal sources.
    The genome weights these and requires minimum agreement.
    """
    # Signal source mapping: gene name -> market feature key
    source_map = {
        "w_mean_reversion": "sig_mean_reversion",
        "w_time_of_day": "sig_time_of_day",
        "w_book_imbalance": "sig_book_imbalance",
        "w_wallet_flow": "sig_wallet_flow",
        "w_informed_flow": "sig_informed_flow",
        "w_cross_timeframe": "sig_cross_timeframe",
        "w_vol_regime": "sig_vol_regime",
        "w_residual_horizon": "sig_residual_horizon",
        "w_ml_scanner": "sig_ml_scanner",
        "w_indicator_consensus": "sig_indicator_consensus",
        "w_chainlink_basis": "sig_chainlink_basis",
    }

    def gval(name: str, default: float = 0.0) -> float:
        entry = genes.get(name, {})
        return float(entry.get("value", default))

    min_active = int(gval("min_signals_active", 2))
    agreement_threshold = gval("signal_agreement_pct", 0.6)

    # Count active signals and their directions
    yes_weight = 0.0
    no_weight = 0.0
    total_weight = 0.0
    active_count = 0
    confidence_sum = 0.0

    for gene_name, feature_key in source_map.items():
        weight = gval(gene_name, 0.0)
        if weight < 0.1:
            continue

        sig_value = market.get(feature_key)
        if sig_value is None:
            continue

        # sig_value > 0 means YES signal, < 0 means NO signal
        # magnitude is confidence
        sig_val = float(sig_value)
        if abs(sig_val) < 0.01:
            continue

        active_count += 1
        if sig_val > 0:
            yes_weight += weight * abs(sig_val)
        else:
            no_weight += weight * abs(sig_val)
        total_weight += weight
        confidence_sum += abs(sig_val) * weight

    if active_count < min_active:
        return None

    # Check agreement
    dominant_weight = max(yes_weight, no_weight)
    if total_weight > 0 and (dominant_weight / (yes_weight + no_weight)) < agreement_threshold:
        return None

    side = "YES" if yes_weight > no_weight else "NO"
    # Confidence: base 0.50 + signal-quality bonus (scaled into [0.50, 0.95])
    raw_conf = (confidence_sum / total_weight) if total_weight > 0 else 0.0
    confidence = min(0.95, 0.50 + raw_conf * 0.40)
    edge = abs(yes_weight - no_weight) / total_weight if total_weight > 0 else 0.0

    return {
        "condition_id": market.get("condition_id"),
        "side": side,
        "entry_price": market.get("entry_price", 0.5),
        "confidence": confidence,
        "edge": edge,
        "hour_et": market.get("hour_et", 12),
        "vpin": market.get("vpin", 0.0),
        "spread": market.get("spread", 0.05),
        "book_imbalance": market.get("book_imbalance", 0.0),
        "outcome": market.get("outcome", "unknown"),
    }


def _load_data(data_path: str) -> list[dict]:
    """Load historical market data with pre-computed signal features."""
    path = Path(data_path)
    if not path.exists():
        return []
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return []


def _empty_result(genome_id: str, reason: str) -> dict:
    return {
        "genome_id": genome_id,
        "fitness": -999.0,
        "win_rate": 0.0,
        "total_signals": 0,
        "total_fills": 0,
        "gross_pnl": 0.0,
        "sharpe": 0.0,
        "max_drawdown": 1.0,
        "profit_factor": 0.0,
        "kelly_fraction": 0.0,
        "p_value": 1.0,
        "kill_reasons": [reason],
        "survived": False,
        "details": {"empty_reason": reason},
    }


def _binomial_p(n: int, k: int, p0: float = 0.50) -> float:
    """One-tailed binomial p-value: P(X >= k | X ~ Bin(n, p0))."""
    if n <= 0 or k < 0:
        return 1.0
    if k > n:
        return 0.0
    p_val = 0.0
    q0 = 1.0 - p0
    for i in range(k, n + 1):
        coeff = math.comb(n, i)
        prob = coeff * (p0 ** i) * (q0 ** (n - i))
        p_val += prob
    return min(p_val, 1.0)


# ---------------------------------------------------------------------------
# Tournament runner
# ---------------------------------------------------------------------------

class TournamentEngine:
    """
    Runs parallel backtests across a population of genomes.

    Uses all available CPU cores. Each genome is evaluated independently
    against the same historical dataset. Results are ranked by fitness.
    """

    def __init__(
        self,
        data_path: str = "",
        max_workers: Optional[int] = None,
        config: Optional[dict] = None,
    ):
        self.data_path = data_path
        self.max_workers = max_workers or max(1, cpu_count() - 1)
        self.config = config or {}
        self._tournament_count = 0

    def run_tournament(
        self,
        genomes: list[StrategyGenome],
        tournament_id: Optional[str] = None,
    ) -> TournamentReport:
        """
        Evaluate all genomes in parallel and return ranked results.

        Args:
            genomes: Population to evaluate
            tournament_id: Optional identifier for this tournament round

        Returns:
            TournamentReport with ranked results (best first)
        """
        self._tournament_count += 1
        tid = tournament_id or f"T{self._tournament_count:04d}"
        started = datetime.now(timezone.utc).isoformat()
        t0 = time.monotonic()

        logger.info(
            "Tournament %s: evaluating %d genomes on %d cores",
            tid, len(genomes), self.max_workers,
        )

        # Serialize genomes for multiprocessing
        work_items = []
        for genome in genomes:
            genome_dict = {
                "genome_id": genome.genome_id,
                "genes": {
                    k: {"value": g.value, "type": g.gene_type.value,
                         "range": [g.lower, g.upper]}
                    for k, g in genome.genes.items()
                },
            }
            work_items.append((genome_dict, self.data_path, self.config))

        # Run parallel evaluation
        raw_results: list[dict] = []

        if self.max_workers <= 1 or len(genomes) <= 2:
            # Sequential for small batches or debugging
            for item in work_items:
                raw_results.append(_evaluate_genome_worker(item))
        else:
            with ProcessPoolExecutor(max_workers=self.max_workers) as executor:
                futures = {
                    executor.submit(_evaluate_genome_worker, item): i
                    for i, item in enumerate(work_items)
                }
                for future in as_completed(futures):
                    try:
                        raw_results.append(future.result())
                    except Exception as e:
                        idx = futures[future]
                        logger.error("Genome eval %d failed: %s", idx, e)
                        raw_results.append(
                            _empty_result(
                                genomes[idx].genome_id if idx < len(genomes) else "?",
                                f"process_error: {str(e)[:100]}",
                            )
                        )

        # Convert to TournamentResult objects
        results = []
        for r in raw_results:
            results.append(TournamentResult(
                genome_id=r["genome_id"],
                fitness=r["fitness"],
                win_rate=r["win_rate"],
                total_signals=r["total_signals"],
                total_fills=r["total_fills"],
                gross_pnl=r["gross_pnl"],
                sharpe=r["sharpe"],
                max_drawdown=r["max_drawdown"],
                profit_factor=r["profit_factor"],
                kelly_fraction=r["kelly_fraction"],
                p_value=r["p_value"],
                kill_reasons=r.get("kill_reasons", []),
                survived=r.get("survived", False),
                eval_time_ms=r.get("eval_time_ms", 0.0),
                details=r.get("details", {}),
            ))

        # Update genome fitness values
        result_map = {r.genome_id: r for r in results}
        for genome in genomes:
            if genome.genome_id in result_map:
                genome.fitness = result_map[genome.genome_id].fitness

        # Sort by fitness (highest first)
        results.sort(key=lambda r: r.fitness, reverse=True)

        survived = [r for r in results if r.survived]
        killed = [r for r in results if not r.survived]

        elapsed_ms = (time.monotonic() - t0) * 1000
        completed = datetime.now(timezone.utc).isoformat()

        fitnesses = [r.fitness for r in results if r.fitness > -900]
        median_fitness = sorted(fitnesses)[len(fitnesses) // 2] if fitnesses else 0.0

        report = TournamentReport(
            tournament_id=tid,
            started_at=started,
            completed_at=completed,
            population_size=len(genomes),
            survived_count=len(survived),
            killed_count=len(killed),
            best_fitness=results[0].fitness if results else 0.0,
            best_genome_id=results[0].genome_id if results else "",
            median_fitness=median_fitness,
            results=results,
            eval_time_total_ms=elapsed_ms,
            cores_used=self.max_workers,
        )

        logger.info(
            "Tournament %s complete: %d survived, %d killed, "
            "best=%.4f (%s), median=%.4f, %.1fs total",
            tid, len(survived), len(killed),
            report.best_fitness, report.best_genome_id,
            report.median_fitness, elapsed_ms / 1000,
        )

        return report

    def evaluate_single(self, genome: StrategyGenome) -> TournamentResult:
        """Evaluate a single genome (for debugging or incremental evaluation)."""
        report = self.run_tournament([genome], tournament_id="single")
        return report.results[0] if report.results else TournamentResult(
            genome_id=genome.genome_id, fitness=-999.0,
            win_rate=0.0, total_signals=0, total_fills=0,
            gross_pnl=0.0, sharpe=0.0, max_drawdown=1.0,
            profit_factor=0.0, kelly_fraction=0.0, p_value=1.0,
            kill_reasons=["eval_failed"], survived=False,
        )
